schemaVersion: 2.0.0
commandTests:
  - name: "dotnet which"
    command: "which"
    args: ["dotnet"]
    expectedOutput: ["/usr/bin/dotnet"]
  - name: "dotnet version"
    command: "dotnet"
    args: [ "--version" ]
    expectedOutput: ["6.0.*"]
  - name: "powershell which"
    command: "which"
    args: ["pwsh"]
    expectedOutput: ["/usr/bin/pwsh"]
  - name: "powershell version"
    command: "pwsh"
    args: ["--version"]
    expectedOutput: ["PowerShell 7.*"]
  - name: "ps-empire help"
    command: "./ps-empire"
    args: ["server", "--help"]
    expectedOutput: ["usage: empire.py server [-h]*"]
  - name: "ps-empire version"
    command: "./ps-empire"
    args: ["server", "--version"]
    expectedOutput: ["4.* BC Security Fork"]
fileExistenceTests:
  - name: 'profiles'
    path: '/empire/empire/server/data/profiles/'
    shouldExist: true
  - name: 'invoke obfuscation'
    path: '/usr/local/share/powershell/Modules/Invoke-Obfuscation/'
    shouldExist: true
  - name: 'sharpire'
    path: '/empire/empire/server/csharp/Covenant/Data/ReferenceSourceLibraries/Sharpire'
    shouldExist: true
  