# This is for running the tests in the Docker file, so we can catch
# issues with the Dockerfile itself.
version: '3'

services:
  test:
    build: ../
    image: bcsecurity/empire-test
    entrypoint: poetry
    command: run python -m pytest .
