[tool.poetry]
name = "empire-bc-security-fork"
version = "5.5.4"
description = ""
authors = ["BC Security <info@bc-security.org>"]
readme = "README.md"
homepage = "https://github.com/BC-SECURITY/Empire"
repository = "https://github.com/BC-SECURITY/Empire.git"
packages = [
    { include = "empire.py" },
    { include = "empire/server/**/*.py" },
    { include = "empire/client/**/*.py" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
urllib3 = "*"
requests = "^2.24.0"
iptools = "*"
macholib = "*"
dropbox = "*"
pyOpenSSL = "*"
zlib_wrapper = "^0.1.3"
netifaces = "*"
jinja2 = "*"
xlutils = "*"
pyparsing = "*"
PyMySQL = "^0.10.1"
SQLAlchemy = "^2.0"
PyYAML = "^6.0.1"
SQLAlchemy-Utc = "^0.14.0"
prompt-toolkit = "^3.0.9"
terminaltables = "^3.1.0"
docopt = "^0.6.2"
humanize = "^3.2.0"
pydantic = "^1.8.1"
pycryptodome = "^3.10.1"
cryptography = "^37.0.3"
fastapi = "0.70"
uvicorn = "^0.14.0"
jq = "^1.2.1"
aiofiles = "^0.7.0"
python-multipart = "^0.0.5"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
websockify = "^0.10.0"
websockets = "^10.1"
pyperclip = "^1.8.2"
pyvnc = {git = "https://github.com/BC-SECURITY/pyVNC.git"}
python-socketio = {extras = ["client"], version = "^5.7.1"}
Flask = "^2.1.2"
pysecretsocks = {git = "https://github.com/BC-SECURITY/PySecretSOCKS.git"}
donut-shellcode = "^1.0.2"
python-obfuscator = "^0.0.2"
pyinstaller = "^5.12"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^23.1.0"
pytest = "^7.2.0"
pytest-timeout = "^2.1.0"
ruff = "^0.0.233"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
supported_extensions = ['pxd', 'py', 'pyi', 'pyx', 'plugin']

[tool.black]
extend-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''
force-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''

#include = '.*\.(plugin)$'

[tool.ruff]
extend-exclude = [
    'empire/server/data',
    'empire/server/downloads',
    'empire/server/common/malleable',
    'empire/client/generated-stagers',
    'empire/client/downloads'
]
# Will revisit line lengths later. Black won't format the strings and comments
# by default. And the experimental flag still has some issues.
# fixes right now: https://github.com/psf/black/issues/2188
extend-ignore = ["E501"]
