schemaVersion: 2.0.0
commandTests:
  - name: "python3.8 which"
    command: "which"
    args: ["python3.8"]
    expectedOutput: ["/usr/local/bin/python3"]
  - name: "python3.8 version"
    command: "python3.8"
    args: ["--version"]
    expectedOutput: ["Python 3.8.*"]
