schemaVersion: 2.0.0
commandTests:
  - name: "python3 which"
    command: "which"
    args: ["python3"]
    expectedOutput: ["/usr/bin/python3"]
  - name: "python3 version"
    command: "python3"
    args: ["--version"]
    expectedOutput: ["Python 3.8.*"]
