schemaVersion: 2.0.0
commandTests:
  - name: "python3.8 which"
    command: "which"
    args: ["python3.8"]
    expectedOutput: ["/usr/local/bin/python3"]
  - name: "python3.8 version"
    command: "python3.8"
    args: ["--version"]
    expectedOutput: ["Python 3.8.*"]
  - name: "mysql which"
    command: "which"
    args: ["mysql"]
    expectedOutput: ["/usr/bin/mysql"]
  - name: "mysql version"
    command: "mysql"
    args: ["--version"]
    expectedOutput: ["mysql  Ver 15.*10.*-MariaDB"]
