schemaVersion: 2.0.0
commandTests:
  - name: "python3 which"
    command: "which"
    args: ["python3"]
    expectedOutput: ["/usr/bin/python3"]
  - name: "python3 version"
    command: "python3"
    args: ["--version"]
    expectedOutput: ["Python 3.9.*"]
  - name: "mysql which"
    command: "which"
    args: ["mysql"]
    expectedOutput: ["/usr/bin/mysql"]
  - name: "mysql version"
    command: "mysql"
    args: ["--version"]
    expectedOutput: ["mysql  Ver 15.*10.*-MariaDB"]
