name: 'Update Starkiller'
description: 'Updates the config.yaml and starkiller submodule to the specified version and commits the change.'
inputs:
  starkiller-version:
    description: 'The branch to merge from'
    required: true
  app-version:
    description: 'The changelog section to update'
    required: true
  repo:
    description: "The starkiller repo to use. If not set, doesn't update the field."
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install minimal python packages
      shell: bash
      run: python -m pip install pyyaml
    # This is technically only needed for the first time we update the public repo, as a bootstrap.
    # After that, the submodule is already initialized to the right repo.
    - name: Update config.yaml repo
      if: ${{ inputs.repo }}
      shell: bash
      run: |
        sed -i "s|repo:.*|repo: ${{ inputs.repo }}|" empire/server/config.yaml
    - name: Update config.yaml ref
      shell: bash
      # this depends on there not being any other keys in teh config named ref
      # if there are, this will break. We could be safer to load/dump the yaml,
      # but would lose the comments.
      run: |
        sed -i "s/ref: .*/ref: ${{ inputs.starkiller-version }}/" empire/server/config.yaml
    - name: Run starkiller update script
      shell: bash
      run: python empire.py sync-starkiller
    - name: Update changelog
      shell: bash
      run: |
        sed -i '/## \[${{ inputs.app-version }}\]/a -   Updated Starkiller to ${{ inputs.starkiller-version }}' CHANGELOG.md
    - name: Commit changes
      shell: bash
      run: |
        git add -A
        git commit --message "Update starkiller version to ${{ inputs.starkiller-version }}"
