name: Public - Create Release Branch
on:
  workflow_dispatch:
    inputs:
      sponsorTag:
        description: 'The tag to merge into master and dev from the sponsors repo. Example: v4.5.2'
        type: string
        required: true

jobs:
  create_release:
    if: ${{ github.repository == 'BC-SECURITY/Empire' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out sponsors code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          repository: 'bc-security/empire-sponsors'
          ref: sponsors-dev
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0
      - name: Add public repo
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Checkout sponsor tag
        run: |
          git checkout ${{ github.event.inputs.sponsorTag }}
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.sponsorTag }}
      - name: Push new branch
        run: git push upstream release/${{ github.event.inputs.sponsorTag }}
      - name: Create pull request into dev
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          head: release/${{ github.event.inputs.sponsorTag }}
          base: dev
          title: ${{ github.event.inputs.sponsorTag }} into dev
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was automatically generated by the `release-public-start` workflow.
            This PR should be merged with a merge commit, not a squash commit.
      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          head: release/${{ github.event.inputs.sponsorTag }}
          base: master
          title: ${{ github.event.inputs.sponsorTag }} into master
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was automatically generated by the `release-public-start` workflow.
            This PR should be merged with a merge commit, not a squash commit.
